// @gm/domain — status/ACL/lifecycle/waiting/routing rules (Part 6 §6.3–6.6).
// Time arithmetic comes only from @gm/time; no Firestore/HTTP here.
export {
  GM_CATEGORIES,
  GM_CATEGORY_KEYS,
  REQUEST_ORIGINS,
  REQUEST_TYPES,
  ROLES,
  SENSITIVITY_REASONS,
  SENSITIVITY_SUBJECTS,
  RequestRejected,
  createRequestDraft,
  defaultSensitivity,
  maintenanceTitle,
  type Actor,
  type ConfidentialChoice,
  type CreateRequestCommand,
  type DocumentDetails,
  type GmCategory,
  type Labelled,
  type MaintenanceDetails,
  type OnBehalfRequester,
  type RequestDraft,
  type RequestOrigin,
  type RequestType,
  type Role,
  type SensitivityReason,
  type SensitivitySubject,
  type ServiceDetails,
} from './request-creation';
export {
  REQUEST_STATUSES,
  LifecycleRejected,
  acceptRequest,
  autoCloseRequest,
  cancelRequest,
  completeRequest,
  confirmCompletion,
  reopenRequest,
  reportNotResolved,
  type ActorCommand,
  type AutoCloseResult,
  type AutoCloseSkipReason,
  type ClosureKind,
  type LifecycleEvent,
  type LifecycleEventKind,
  type LifecycleResult,
  type LifecycleState,
  type RequestStatus,
} from './lifecycle';
export {
  removeConfidentialFlag,
  type ConfidentialFlagRemovedEvent,
  type ConfidentialityState,
} from './confidentiality';
export {
  DEFAULT_WORKING_MORNING_TIME,
  MAX_TEAM_CONTACTS,
  WAITING_PARTY_KINDS,
  changeWaitingParty,
  currentWaitingInterval,
  endWaitingInterval,
  enterWaiting,
  followUp,
  planWaiting,
  respondWaitingParty,
  resumeWork,
  type EndedWaitingInterval,
  type EnterWaitingResult,
  type ExternalPartyKind,
  type FollowUpResult,
  type ReminderOutcome,
  type WaitingCommand,
  type WaitingEvent,
  type WaitingFields,
  type WaitingNotice,
  type WaitingOn,
  type WaitingOnInput,
  type WaitingPartyKind,
  type WaitingPlan,
  type WaitingRequestState,
  type WaitingResult,
} from './waiting';
export {
  PRESENCE_LABELS,
  PRESENCE_STATUSES,
  effectivePresence,
  isOnLeave,
  resetPresence,
  setPresence,
  type EffectivePresence,
  type GmProfile,
  type PresenceChangedEvent,
  type PresenceResetResult,
  type PresenceStatus,
} from './presence';
export {
  INTERNAL_WORK_LABEL,
  NO_CURRENT_WORK_LABEL,
  currentWork,
  releaseFocusIfEnded,
  setFocus,
  type CurrentWork,
  type CurrentWorkCandidate,
  type FocusEvent,
  type FocusRequest,
} from './focus';
export {
  routeNewRequest,
  type RouteNewRequestInput,
  type RoutingNotice,
  type RoutingReason,
  type RoutingResult,
  type RoutingSettings,
} from './routing';
