// @gm/domain — status/ACL/lifecycle/waiting/routing rules (Part 6 §6.3–6.6).
// Time arithmetic comes only from @gm/time; no Firestore/HTTP here.
export {
  GM_CATEGORIES,
  GM_CATEGORY_KEYS,
  REQUEST_ORIGINS,
  REQUEST_TYPES,
  ROLES,
  SENSITIVITY_REASONS,
  SENSITIVITY_SUBJECTS,
  RequestRejected,
  createRequestDraft,
  defaultSensitivity,
  maintenanceTitle,
  type Actor,
  type ConfidentialChoice,
  type CreateRequestCommand,
  type RelatedChoice,
  type DocumentDetails,
  type GmCategory,
  type Labelled,
  type MaintenanceDetails,
  type OnBehalfRequester,
  type RequestDraft,
  type RequestOrigin,
  type RequestType,
  type Role,
  type SensitivityReason,
  type SensitivitySubject,
  type ServiceDetails,
} from './request-creation';
export {
  REQUEST_STATUSES,
  LifecycleRejected,
  acceptRequest,
  autoCloseRequest,
  cancelRequest,
  completeRequest,
  confirmCompletion,
  reopenRequest,
  reportNotResolved,
  type ActorCommand,
  type AutoCloseResult,
  type AutoCloseSkipReason,
  type ClosureKind,
  type LifecycleEvent,
  type LifecycleEventKind,
  type LifecycleResult,
  type LifecycleState,
  type RequestStatus,
} from './lifecycle';
export {
  markConfidential,
  removeConfidentialFlag,
  type ConfidentialFlagRemovedEvent,
  type ConfidentialFlagSetEvent,
  type ConfidentialityState,
  type FlaggableState,
} from './confidentiality';
export {
  DEFAULT_WORKING_MORNING_TIME,
  MAX_TEAM_CONTACTS,
  WAITING_PARTY_KINDS,
  changeWaitingParty,
  currentWaitingInterval,
  endWaitingInterval,
  enterWaiting,
  followUp,
  planWaiting,
  respondWaitingParty,
  resumeWork,
  type EndedWaitingInterval,
  type EnterWaitingResult,
  type ExternalPartyKind,
  type FollowUpResult,
  type ReminderOutcome,
  type WaitingCommand,
  type WaitingEvent,
  type WaitingFields,
  type WaitingNotice,
  type WaitingOn,
  type WaitingOnInput,
  type WaitingPartyKind,
  type WaitingPlan,
  type WaitingRequestState,
  type WaitingResult,
} from './waiting';
export {
  PRESENCE_KINDS,
  PRESENCE_KIND_LABELS,
  effectivePresence,
  isOnLeave,
  presenceLabel,
  resetPresence,
  setPresence,
  type EffectivePresence,
  type GmProfile,
  type LocationOption,
  type PresenceChangedEvent,
  type PresenceKind,
  type PresenceResetResult,
  type PresenceStatus,
} from './presence';
export {
  INTERNAL_WORK_LABEL,
  NO_CURRENT_WORK_LABEL,
  currentWork,
  releaseFocusIfNotInProgress,
  setFocus,
  type CurrentWork,
  type CurrentWorkCandidate,
  type FocusEvent,
  type FocusRequest,
} from './focus';
export {
  allGmNoticeRecipients,
  routeNewRequest,
  type GmMember,
  type RouteNewRequestInput,
  type RoutingNotice,
  type RoutingReason,
  type RoutingResult,
  type RoutingSettings,
} from './routing';
export {
  REQUEST_NUMBER_PREFIXES,
  formatRequestNumber,
  nextRequestSequence,
  requestNumberPrefix,
  type DeploymentEnvironment,
} from './request-number';
export { watchRequest, type WatchOutcome, type WatchState } from './watch';
export {
  addRelatedPersons,
  planRelatedAddition,
  removeRelatedPerson,
  type RelatedAdditionPlan,
  type RelatedPeopleState,
  type RelatedPersonRemovedEvent,
  type RelatedPersonsAddedEvent,
} from './related-people';
export { boardSection, isOnLiveBoard, type BoardFacts, type BoardSection } from './board';
export {
  canAttachToRequest,
  canContributeAsWatcher,
  canReadGmProjections,
  canReadPublicSummaries,
  canReadRequestDetail,
  isActiveViewer,
  type AccessViewer,
  type RequestAclFacts,
} from './acl';
export {
  DELIVERY_LEASE_MS,
  DELIVERY_STATES,
  SETTLED_DELIVERY_STATES,
  chooseDeliveryChannel,
  claimDelivery,
  isDeliveryState,
  settleDelivery,
  type DeliveryChannel,
  type DeliveryClaim,
  type DeliveryLeaseState,
  type DeliveryOutcome,
  type DeliveryRecipient,
  type DeliverySettlement,
  type DeliveryState,
} from './delivery';
export {
  BOUNDED_RETRY,
  JOB_LEASE_MS,
  JOB_STATES,
  SCHEDULED_WORK_KINDS,
  TICK_INTERVAL_MS,
  TICK_LEASE_MS,
  TICK_SCHEDULE,
  TICK_STEPS,
  TICK_WORK_BUDGET_MS,
  claimJob,
  claimTick,
  isScheduledWorkKind,
  nextRetryAt,
  settleJob,
  type JobClaim,
  type JobLeaseState,
  type JobOutcome,
  type JobSettlement,
  type JobState,
  type ScheduledWorkKind,
  type TickStep,
} from './scheduled-work';
