// @gm/domain — status/ACL/lifecycle/waiting/routing rules (Part 6 §6.3–6.6).
// Time arithmetic comes only from @gm/time; no Firestore/HTTP here.
export {
  GM_CATEGORIES,
  GM_CATEGORY_KEYS,
  REQUEST_ORIGINS,
  REQUEST_TYPES,
  ROLES,
  SENSITIVITY_SUBJECTS,
  RequestRejected,
  createRequestDraft,
  defaultSensitivity,
  maintenanceTitle,
  type Actor,
  type ConfidentialChoice,
  type CreateRequestCommand,
  type DocumentDetails,
  type GmCategory,
  type Labelled,
  type MaintenanceDetails,
  type OnBehalfRequester,
  type RequestDraft,
  type RequestOrigin,
  type RequestType,
  type Role,
  type SensitivitySubject,
  type ServiceDetails,
} from './request-creation';
